config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'couriers#index'

  resources :couriers do
    resources :packages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  validates_presence_of :name
  validates :email, presence: true, uniqueness: true

  has_many :packages, :dependent => :destroy
end

app/models/package.rb
class Package < ApplicationRecord
  validates :tracking_number, presence: true, uniqueness: true

  belongs_to :courier
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: [:show, :edit, :update, :destroy]

  def index
    @couriers = Courier.all
  end

  def show
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @courier.update(courier_params)
      redirect_to @courier
    else
      render :new
    end
  end

  def destroy
    @courier.destroy

    redirect_to couriers_path
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_courier, only: :create

  def create
    package = @courier.packages.new(package_params)

    package.save

    redirect_to @courier
  end

  private

  def set_courier
    @courier = Courier.find(params[:courier_id])
  end

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/edit.haml
%h1 Edit Courier

= render 'couriers/partials/courier_form', courier: @courier,
         button_text: 'Update Courier'

app/views/couriers/index.haml
%h1 Couriers

= link_to 'Create Courier', new_courier_path

- @couriers.each do |courier|
  %table
    %tr
      %td= courier.name
      %td= courier.email
      %td= link_to 'Show', courier_path(courier)
      %td= link_to 'Edit', edit_courier_path(courier)
      %td= link_to 'Destroy', courier_path(courier), method: :delete

app/views/couriers/new.haml
%h1 New Courier

= render 'couriers/partials/courier_form', courier: @courier,
         button_text: 'Create Courier'

app/views/couriers/partials/_courier_form.haml
= form_with(model: courier) do |form|
  = form.label(:name, 'Enter Name:')
  = form.text_field(:name)
  %br

  = form.label(:email, 'Enter Email:')
  = form.text_field(:email)
  %br

  = form.submit button_text

app/views/couriers/show.haml
%h1 Courier Profile

%h2 Courier Name
%h3= @courier.name
%h2 Courier Email
%h3= @courier.email

%h2 Add New Package

= render 'shared/package_form', courier: @courier

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DeliveryApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_package_form.haml
= form_with(url: courier_packages_path(courier), scope: 'package') do |form|
  = form.label(:tracking_number, 'Enter Tracking Number')
  = form.text_field :tracking_number
  %br

  = form.label(:delivery_status, "Package is delivered ?")
  = form.check_box :delivery_status
  %br

  = form.submit 'Add Package'